### ISSUE TITLE
Error: Cannot load M3U8: 404 found

### ISSUE THREAD

**Issue by roelbeun** [loek17/iTVOnline.bundle#1]
Hi,

Ik krijg bovenstaande error. Zijn de URL's veranderd? Is dit te repareren?

Ik wil graag voor je testen om zo het project nieuw leven in te blazen.

Verneem graag, dank.

**Comment by loek17** [comment]
Hoi,

Bedankt voor je interesse. Het probleem zit niet bij de url maar bij de beveiliging van de tv streams. Deze is kort na dat ik de plug-in gemaakt heb zodanig verbetert door KPN ( ssl en certificaten en zo) dat het voor mij onmogelijk werd om nog de plug-in werkend te krijgen. 

Het project nieuw leven inblazen gaat dus  niet meer lukken naar mijn mening. 

Met vriendelijk groet,

Loek17

**Comment by roelbeun** [comment]
Dank voor je snelle reactie. Ik zal er dan geen tijd in gaan steken. Toch bedankt!
